/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // MD3 Full Token Set (from product pages)
        'surface-container-highest': '#353534',
        'background': '#131313',
        'surface-container-low': '#1c1b1b',
        'primary-fixed': '#d2f000',
        'on-primary-container': '#5d6b00',
        'on-secondary-fixed-variant': '#394857',
        'primary-container': '#d2f000',
        'on-secondary-fixed': '#0d1d2a',
        'inverse-primary': '#576500',
        'error-container': '#93000a',
        'tertiary-container': '#c8e8f1',
        'on-primary-fixed-variant': '#414c00',
        'surface': '#131313',
        'on-tertiary-fixed': '#001f26',
        'tertiary': '#ffffff',
        'surface-container-high': '#2a2a2a',
        'surface-tint': '#b8d300',
        'outline': '#909378',
        'surface-variant': '#353534',
        'on-primary-fixed': '#191e00',
        'on-primary': '#2c3400',
        'primary': '#ffffff',
        'inverse-on-surface': '#313030',
        'primary-fixed-dim': '#b8d300',
        'outline-variant': '#454932',
        'surface-container-lowest': '#0e0e0e',
        'surface-container': '#201f1f',
        'tertiary-fixed-dim': '#acccd4',
        'tertiary-fixed': '#c8e8f1',
        'on-secondary-container': '#a7b7c8',
        'on-error': '#690005',
        'secondary-fixed-dim': '#b8c8da',
        'secondary': '#b8c8da',
        'on-error-container': '#ffdad6',
        'surface-bright': '#393939',
        'error': '#ffb4ab',
        'on-surface': '#e5e2e1',
        'surface-dim': '#131313',
        'on-tertiary-fixed-variant': '#2e4b52',
        'secondary-fixed': '#d4e4f6',
        'inverse-surface': '#e5e2e1',
        'on-tertiary': '#16343b',
        'on-background': '#e5e2e1',
        'on-tertiary-container': '#4b6971',
        'secondary-container': '#394857',
        'on-surface-variant': '#c6c9ab',
        'on-secondary': '#223240',
      },
      fontFamily: {
        headline: ['Public Sans', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Space Grotesk', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
