

export default function DevelopmentInsights() {
  const aiColor = '#C8FF00'; // Lime green
  const humanColor = '#00E5FF'; // Cyan

  return (
    <section className="py-16 sm:py-24 px-4 sm:px-6 border-t border-outline-variant/10 bg-surface">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="flex flex-col lg:flex-row justify-between items-start lg:items-end mb-10 sm:mb-12 gap-6">
          <div>
            <span className="font-label text-primary-fixed text-sm uppercase tracking-widest mb-2 block">AI TELEMETRY</span>
            <h2 className="text-3xl sm:text-5xl font-black font-headline tracking-tighter uppercase text-white leading-none">
              DEVELOPMENT INSIGHTS
            </h2>
            <div className="mt-4 flex flex-wrap items-center gap-3">
              <span className="bg-surface-container-high px-2 py-1 text-on-surface-variant font-mono text-[10px] sm:text-xs flex items-center gap-1 uppercase border border-outline-variant/20">
                <span className="material-symbols-outlined text-[14px] animate-spin-slow">sync</span>
                LAST SYNC: JUST NOW
              </span>
              <span className="text-outline-variant hidden sm:block">•</span>
              <span className="text-on-surface font-mono text-[10px] sm:text-xs uppercase tracking-widest">
                SHOWING TELEMETRY OF LAST WEEK
              </span>
            </div>
          </div>
        </div>

        {/* Dashboard Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-4 lg:gap-6">
          
          {/* AI Code Contribution */}
          <div className="col-span-1 lg:col-span-6 bg-[#161616] border border-outline-variant/20 p-6 sm:p-8 flex flex-col justify-between scanline relative group overflow-hidden">
            <div className="absolute top-0 right-0 w-64 h-64 bg-primary-fixed/5 rounded-full blur-3xl -translate-y-1/2 translate-x-1/2 group-hover:bg-primary-fixed/10 transition-colors pointer-events-none"></div>
            <div>
              <div className="flex items-center gap-2 mb-6">
                <div className="w-1.5 h-1.5 rounded-full" style={{ backgroundColor: aiColor }}></div>
                <span className="font-label text-xs text-outline-variant uppercase tracking-widest">AI CODE CONTRIBUTION</span>
              </div>
              <div className="text-6xl sm:text-8xl font-mono font-black tracking-tighter" style={{ color: aiColor }}>
                95%
              </div>
              <p className="mt-4 text-on-surface font-body max-w-sm text-sm sm:text-base leading-relaxed">
                of all code written this month was <strong className="text-white font-semibold">generated by Copilot AI</strong>
              </p>
            </div>
            
            <div className="mt-10 sm:mt-12">
              <div className="flex justify-between font-mono text-xs mb-2">
                <span style={{ color: aiColor }}>AI 95%</span>
                <span style={{ color: humanColor }}>HUMAN 5%</span>
              </div>
              <div className="h-2 bg-surface-container-highest w-full overflow-hidden flex">
                <div className="h-full relative" style={{ width: '95%', backgroundColor: aiColor }}>
                  {/* Subtle animation line inside progress bar */}
                  <div className="absolute top-0 left-0 bottom-0 w-8 bg-white/30 skew-x-12 blur-[2px] animate-[slide-right_2s_infinite]"></div>
                </div>
                <div className="h-full" style={{ width: '5%', backgroundColor: humanColor }}></div>
              </div>
            </div>
          </div>

          {/* Lines of Code Written */}
          <div className="col-span-1 lg:col-span-6 bg-[#161616] border border-outline-variant/20 p-6 sm:p-8 flex flex-col justify-between group">
            <div>
              <div className="flex items-center gap-2 mb-6">
                <div className="w-1.5 h-1.5 rounded-full bg-outline-variant"></div>
                <span className="font-label text-xs text-outline-variant uppercase tracking-widest">LINES OF CODE WRITTEN</span>
              </div>
              <div className="text-6xl sm:text-8xl font-mono font-black text-white tracking-tighter">
                2,346
              </div>
              <p className="mt-4 text-on-surface-variant font-body text-sm sm:text-base">
                lines written by <strong className="text-white font-semibold">AI</strong> vs <strong className="text-white font-semibold">124</strong> by humans this month
              </p>
            </div>
            
            <div className="mt-10 sm:mt-12">
              <div className="grid grid-cols-2 gap-4 mb-4">
                <div>
                  <div className="text-2xl font-mono font-bold" style={{ color: aiColor }}>2,346</div>
                  <div className="text-[10px] font-label text-outline-variant uppercase mt-1">AI Lines Added</div>
                </div>
                <div>
                  <div className="text-2xl font-mono font-bold" style={{ color: humanColor }}>124</div>
                  <div className="text-[10px] font-label text-outline-variant uppercase mt-1">Human Lines Added</div>
                </div>
              </div>
              <div className="h-2 bg-surface-container-highest w-full overflow-hidden flex">
                <div className="h-full relative group-hover:brightness-110 transition-all" style={{ width: '95%', backgroundColor: aiColor }}></div>
                <div className="h-full relative group-hover:brightness-110 transition-all" style={{ width: '5%', backgroundColor: humanColor }}></div>
              </div>
            </div>
          </div>

          {/* Weekly Commit Activity */}
          <div className="col-span-1 lg:col-span-7 bg-[#161616] border border-outline-variant/20 p-6 sm:p-8 flex flex-col">
            <div className="flex justify-between flex-wrap gap-4 items-center mb-8">
              <div className="flex items-center gap-2">
                <span className="material-symbols-outlined text-outline-variant text-lg">stacked_line_chart</span>
                <h3 className="font-label text-sm text-white uppercase tracking-widest font-bold">Weekly Commit Activity</h3>
              </div>
              <div className="flex gap-4 font-mono text-[10px] uppercase">
                <div className="flex items-center gap-1.5">
                  <div className="w-2 h-2" style={{ backgroundColor: aiColor }}></div>
                  <span className="text-on-surface-variant">AI Commits</span>
                </div>
                <div className="flex items-center gap-1.5">
                  <div className="w-2 h-2" style={{ backgroundColor: humanColor }}></div>
                  <span className="text-on-surface-variant">Human Commits</span>
                </div>
              </div>
            </div>
            
            {/* Chart Area */}
            <div className="flex-1 relative mt-4 min-h-[200px]">
              {/* Grid Lines */}
              <div className="absolute inset-x-0 inset-y-0 flex flex-col justify-between border-l border-b border-outline-variant/20">
                {[13, 9, 4, 0].map((val, i) => (
                  <div key={i} className={`w-full h-[1px] ${i === 3 ? 'bg-transparent' : 'bg-outline-variant/10'}`}>
                    <span className="absolute -left-5 -translate-y-1/2 font-mono text-[10px] text-outline-variant">{val}</span>
                  </div>
                ))}
              </div>
              
              {/* Bars */}
              <div className="absolute inset-0 flex justify-around items-end ml-4 pt-4 px-2">
                {[
                  { day: 'Mar 13', ai: 80, human: 0 },
                  { day: 'Mar 14', ai: 95, human: 5 },
                  { day: 'Mar 15', ai: 90, human: 2 },
                  { day: 'Mar 16', ai: 70, human: 0 },
                  { day: 'Mar 17', ai: 100, human: 5 },
                  { day: 'Mar 18', ai: 65, human: 2 },
                  { day: 'Mar 19', ai: 85, human: 5 },
                  { day: 'Mar 20', ai: 95, human: 0 }
                ].map((data, i) => (
                  <div key={i} className="flex gap-1 sm:gap-2 items-end h-full w-full justify-center group/bar">
                    <div 
                      className="w-4 sm:w-10 relative cursor-pointer hover:brightness-125 transition-all" 
                      style={{ height: `${data.ai}%`, backgroundColor: aiColor }}
                    >
                      <div className="opacity-0 group-hover/bar:opacity-100 absolute -top-8 left-1/2 -translate-x-1/2 bg-surface text-white text-xs font-mono py-1 px-2 border border-outline-variant/30 pointer-events-none transition-opacity z-10">
                        {Math.round(data.ai * 0.05)}
                      </div>
                    </div>
                    <div 
                      className="w-4 sm:w-10 relative cursor-pointer hover:brightness-125 transition-all" 
                      style={{ height: `${data.human}%`, backgroundColor: humanColor }}
                    ></div>
                  </div>
                ))}
              </div>
            </div>
            
            {/* X-Axis Labels */}
            <div className="flex justify-around ml-4 mt-3 px-2 font-mono text-[10px] text-outline-variant uppercase">
              {['Mar 13', 'Mar 14', 'Mar 15', 'Mar 16', 'Mar 17', 'Mar 18', 'Mar 19', 'Mar 20'].map(day => (
                <div key={day} className="w-4 sm:w-10 text-center truncate">{day}</div>
              ))}
            </div>
          </div>

          {/* Contributors Table */}
          <div className="col-span-1 lg:col-span-5 bg-[#161616] border border-outline-variant/20 p-6 sm:p-8 flex flex-col">
            <div className="flex items-center gap-2 mb-8">
              <span className="material-symbols-outlined text-outline-variant text-lg">group</span>
              <h3 className="font-label text-sm text-white uppercase tracking-widest font-bold">Contributors</h3>
            </div>
            
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="border-b border-outline-variant/20">
                  <th className="pb-3 text-[10px] font-label uppercase text-outline-variant tracking-widest w-1/2">User</th>
                  <th className="pb-3 text-[10px] font-label uppercase text-outline-variant tracking-widest text-right">Commits</th>
                  <th className="pb-3 text-[10px] font-label uppercase text-outline-variant tracking-widest text-right">Lines+</th>
                  <th className="pb-3 text-[10px] font-label uppercase text-outline-variant tracking-widest text-right">Lines-</th>
                  <th className="pb-3 text-[10px] font-label uppercase text-outline-variant tracking-widest text-right">LOC%</th>
                </tr>
              </thead>
              <tbody className="font-mono text-sm">
                <tr className="border-b border-outline-variant/10 hover:bg-surface-bright/50 transition-colors">
                  <td className="py-4 flex items-center gap-3">
                    <div className="w-6 h-6 sm:w-8 sm:h-8 flex items-center justify-center bg-primary-fixed/10 border border-primary-fixed/30 text-[10px] font-bold" style={{ color: aiColor }}>AI</div>
                    <span className="text-white font-bold">Copilot AI</span>
                  </td>
                  <td className="py-4 text-right text-on-surface">35</td>
                  <td className="py-4 text-right" style={{ color: aiColor }}>+2,346</td>
                  <td className="py-4 text-right text-error">-312</td>
                  <td className="py-4 text-right">
                    <div className="flex items-center justify-end gap-2">
                      <div className="w-8 h-1 bg-surface-container-highest">
                        <div className="h-full" style={{ width: '95%', backgroundColor: aiColor }}></div>
                      </div>
                      <span className="text-on-surface text-xs w-8">95%</span>
                    </div>
                  </td>
                </tr>
                <tr className="border-b border-outline-variant/10 hover:bg-surface-bright/50 transition-colors">
                  <td className="py-4 flex items-center gap-3">
                    <div className="w-6 h-6 sm:w-8 sm:h-8 flex items-center justify-center bg-[#00E5FF]/10 border border-[#00E5FF]/30 text-[10px] font-bold text-[#00E5FF]">RN</div>
                    <span className="text-on-surface-variant text-xs sm:text-sm truncate max-w-[80px] sm:max-w-none">RudreshNarwal</span>
                  </td>
                  <td className="py-4 text-right text-on-surface">7</td>
                  <td className="py-4 text-right text-[#00E5FF]">+86</td>
                  <td className="py-4 text-right text-error">-24</td>
                  <td className="py-4 text-right">
                    <div className="flex items-center justify-end gap-2">
                      <div className="w-8 h-1 bg-surface-container-highest">
                        <div className="h-full" style={{ width: '3.5%', backgroundColor: humanColor }}></div>
                      </div>
                      <span className="text-on-surface text-xs w-8">3.5%</span>
                    </div>
                  </td>
                </tr>
                <tr className="hover:bg-surface-bright/50 transition-colors">
                  <td className="py-4 flex items-center gap-3">
                    <div className="w-6 h-6 sm:w-8 sm:h-8 flex items-center justify-center bg-[#00E5FF]/10 border border-[#00E5FF]/30 text-[10px] font-bold text-[#00E5FF]">RP</div>
                    <span className="text-on-surface-variant text-xs sm:text-sm truncate max-w-[80px] sm:max-w-none">ravipiplani</span>
                  </td>
                  <td className="py-4 text-right text-on-surface">3</td>
                  <td className="py-4 text-right text-[#00E5FF]">+38</td>
                  <td className="py-4 text-right text-error">-16</td>
                  <td className="py-4 text-right">
                    <div className="flex items-center justify-end gap-2">
                      <div className="w-8 h-1 bg-surface-container-highest">
                        <div className="h-full" style={{ width: '1.5%', backgroundColor: humanColor }}></div>
                      </div>
                      <span className="text-on-surface text-xs w-8">1.5%</span>
                    </div>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>

          {/* Bottom Stats Row */}
          <div className="col-span-1 lg:col-span-4 bg-[#161616] border border-outline-variant/20 p-6 flex flex-col justify-center">
            <span className="font-label text-[10px] text-outline-variant uppercase tracking-widest mb-2 block">TOTAL COMMITS</span>
            <div className="text-4xl font-mono font-black text-white">45</div>
            <div className="mt-2 text-xs font-mono text-on-surface-variant">
              <span style={{ color: aiColor }}>35 by AI</span> • 10 by humans
            </div>
          </div>

          <div className="col-span-1 lg:col-span-4 bg-[#161616] border border-outline-variant/20 p-6 flex flex-col justify-center relative overflow-hidden">
            <div className="absolute top-0 w-full h-1 bg-gradient-to-r from-transparent via-[#C8FF00]/50 to-transparent opacity-50"></div>
            <span className="font-label text-[10px] text-outline-variant uppercase tracking-widest mb-2 block">NET LINES ADDED</span>
            <div className="text-4xl font-mono font-black" style={{ color: aiColor }}>+2,118</div>
            <div className="mt-2 text-xs font-mono text-on-surface-variant">
              +2,470 added / -352 deleted
            </div>
          </div>

          <div className="col-span-1 lg:col-span-4 bg-[#161616] border border-outline-variant/20 p-6 flex flex-col justify-center">
            <span className="font-label text-[10px] text-outline-variant uppercase tracking-widest mb-2 block">AI EFFICIENCY RATIO</span>
            <div className="text-4xl font-mono font-black text-white">9.5<span className="text-primary-fixed text-2xl">×</span></div>
            <div className="mt-2 text-xs font-mono text-on-surface-variant">
              AI writes 9.5× more code per commit
            </div>
          </div>

        </div>
      </div>

      <style>{`
        @keyframes slide-right {
          0% { transform: translateX(-100%); }
          100% { transform: translateX(1000%); }
        }
      `}</style>
    </section>
  );
}
